<div>
<div className="div-line">
<h2>PRICES</h2>
    <Table striped bordered hover variant="dark" size="sm">
        <thead>
            <tr>
                <th><FontAwesomeIcon icon={faChartPie} /></th>
                <th>CRYPTO</th>
                <th>PRICE</th>
                <th>VALUE</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>{names[0]}</td>
                <td>{dollaSign}{currentprice[0]}</td>
                <td>{dollaSign}{value[0]}</td>
            </tr>
            <tr>
                <td>2</td>
                <td>{names[1]}</td>
                <td>{dollaSign}{currentprice[1]}</td>
                <td>{dollaSign}{value[1]}</td>
            </tr>
            <tr>
                <td>3</td>
                <td>{names[2]}</td>
                <td>{dollaSign}{currentprice[2]}</td>
                <td>{dollaSign}{value[2]}</td>
            </tr>
            <tr>
                <td>4</td>
                <td>{names[3]}</td>
                <td>{dollaSign}{currentprice[3]}</td>
                <td>{dollaSign}{value[3]}</td>
            </tr>
            <tr>
                <td>5</td>
                <td>{names[4]}</td>
                <td>{dollaSign}{currentprice[4]}</td>
                <td>{dollaSign}{value[4]}</td>
            </tr>
            <tr>
                <td>6</td>
                <td>{names[5]}</td>
                <td>{dollaSign}{currentprice[5]}</td>
                <td>{dollaSign}{value[5]}</td>
            </tr>
            <tr>
                <td>7</td>
                <td>{names[6]}</td>
                <td>{dollaSign}{currentprice[6]}</td>
                <td>{dollaSign}{value[6]}</td>
            </tr>
            <tr>
                <td>8</td>
                <td>{names[7]}</td>
                <td>{dollaSign}{currentprice[7]}</td>
                <td>{dollaSign}{value[7]}</td>
            </tr>
            <tr>
                <td>9</td>
                <td>{names[8]}</td>
                <td>{dollaSign}{currentprice[8]}</td>
                <td>{dollaSign}{value[8]}</td>
            </tr>
            <tr>
                <td>10</td>
                <td>{names[9]}</td>
                <td>{dollaSign}{currentprice[9]}</td>
                <td>{dollaSign}{value[9]}</td>
            </tr>
            <tr>
                <td>11</td>
                <td>{names[10]}</td>
                <td>{dollaSign}{currentprice[10]}</td>
                <td>{dollaSign}{value[10]}</td>
            </tr>
            <tr>
                <td>12</td>
                <td>{names[11]}</td>
                <td>{dollaSign}{currentprice[11]}</td>
                <td>{dollaSign}{value[11]}</td>
            </tr>
        </tbody>
    </Table>
</div>
</div>
